# Generated by Django 6.0.5 on 2026-05-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Modelo')),
                ('archivo', models.FileField(upload_to='bim_models/', verbose_name='Archivo IFC')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión')),
                ('cargado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo BIM',
                'verbose_name_plural': 'Modelos BIM',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='BIMElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=50, unique=True, verbose_name='GUID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('activity_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='costs.activitykit', verbose_name='Kit de Actividades')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='bim.bimmodel', verbose_name='Modelo BIM')),
            ],
            options={
                'verbose_name': 'Elemento BIM',
                'verbose_name_plural': 'Elementos BIM',
            },
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_models', to='bim.project', verbose_name='Proyecto'),
        ),
    ]
