# Generated by Django 6.0.5 on 2026-05-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_kit', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código del Kit')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Kit')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_kits', to='bim.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Kit de Cronograma',
                'verbose_name_plural': 'Kits de Cronograma',
            },
        ),
        migrations.CreateModel(
            name='ActividadCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.CharField(max_length=50, verbose_name='Código de Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('fase', models.CharField(blank=True, default='', max_length=100, verbose_name='Fase')),
                ('sector', models.CharField(blank=True, default='', max_length=100, verbose_name='Sector')),
                ('base_actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='schedule.actividadcronograma', verbose_name='Actividad Base (Maestra)')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_actividades', to='bim.project', verbose_name='Proyecto')),
                ('kit_cronograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_actividades', to='schedule.kitcronograma', verbose_name='Kit de Cronograma')),
            ],
            options={
                'verbose_name': 'Actividad de Cronograma',
                'verbose_name_plural': 'Actividades de Cronograma',
                'constraints': [models.UniqueConstraint(condition=models.Q(('kit_cronograma__isnull', True), ('proyecto__isnull', True)), fields=('codigo_actividad',), name='unique_master_schedule_codigo')],
            },
        ),
    ]
