# Generated by Django 6.0.5 on 2026-05-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_activity_kit_activities_refactor'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcronograma',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_actividades', to='costs.masterformat', verbose_name='División MasterFormat'),
        ),
    ]
