# Generated by Django 6.0.5 on 2026-05-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.CharField(max_length=50, unique=True, verbose_name='Código de Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad')),
                ('cu_total', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo Unitario Total')),
                ('material', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Material')),
                ('mano_obra', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Mano de Obra')),
                ('equipo', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='MasterFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_code', models.CharField(max_length=20, unique=True, verbose_name='Código de División')),
                ('division_name', models.CharField(max_length=255, verbose_name='Nombre de la División')),
            ],
            options={
                'verbose_name': 'MasterFormat',
                'verbose_name_plural': 'MasterFormat Divisions',
            },
        ),
        migrations.CreateModel(
            name='ActivityKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Kit')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activities', models.ManyToManyField(related_name='kits', to='costs.activity', verbose_name='Actividades')),
            ],
            options={
                'verbose_name': 'Kit de Actividades',
                'verbose_name_plural': 'Kits de Actividades',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='costs.masterformat', verbose_name='División MasterFormat'),
        ),
    ]
